### ISSUE TITLE
[Add device] Do not clear device id information

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/map#148]
![image](https://github.com/hello-nrfcloud/web/assets/188915/45404607-5912-4ba5-8bb7-a3a2faa63ebe)

If you click continue in the above screen, the device ID information is lost.
Improve this flow and show it when presenting the credentials.

**Comment by coderbyheart** [comment]
Thanks @maxd-nordic for bringing this up. The device Id is in the email you receive to confirm it:

> [hello.nrfcloud.com] › Verify device ownership for device map-66ba2df5-9754-4dbf-8d59-dd3489d00c10: 3GUJRJ

But I think it would be good to send the user an email with the certificate and all device details. How does that sound?

**Comment by maxd-nordic** [comment]
That sounds like a good idea. Putting the relevant info in a mail is effective in making sure it doesn't get lost. Maybe combine it with #149.
