### ISSUE TITLE
[Add device] Custom device type

### ISSUE THREAD

**Issue by maxd-nordic** [hello-nrfcloud/map#150]

**Comment by coderbyheart** [comment]
Please explain @maxd-nordic

**Comment by maxd-nordic** [comment]
When adding a new device, there should be a catch-all "custom" option for devices that are not officially supported. The device details shown would then rely on the device reporting supported objects.

**Comment by coderbyheart** [comment]
This is not good for the end user, the device type serves as a user friendly description for the purpose of the device. All devices must use a well defined device type. If you're in a pinch you can always pick one of the existing ones.
