### ISSUE TITLE
Minimap: location hexagons not visible

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/map#381]
Example: https://hello.nrfcloud.com/map/#id:bestower-conyrine-overrich!m:6.051610607029811:62.22904970876206,5.350398918615497!t:ko;location:di;14201;2:di;14201;0:di;14201;1

![image](https://github.com/user-attachments/assets/15ea54c6-4f9b-4d83-ac8e-39022e184f3e)

**Comment by Aarshit-33** [comment]
can I work on this issue or is it already solved ? 
@coderbyheart

**Comment by coderbyheart** [comment]
Yes sure, it hasn't been solved yet.

**Comment by Aarshit-33** [comment]
can you provide the values to be set for the environment variables ? like MapRegion, MapName and ApiKey ?

**Comment by coderbyheart** [comment]
You can set this up in your own AWS account using https://github.com/hello-nrfcloud/aws-map
